analyzer:
  errors:
    sort_constructors_first: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
   # Common lint rules for style and easy reading 
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    always_declare_return_types: true
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    sort_constructors_first: true
    # prefer_relative_imports: true
    avoid_unused_constructor_parameters: true
    depend_on_referenced_packages: true

    # Lint rules for flutter
    use_build_context_synchronously: true  # Avoid using BuildContext synchronously in the widget tree
    avoid_unnecessary_containers: true  # Avoid using unnecessary containers in the widget tree
    prefer_const_literals_to_create_immutables: true  # Prefer using const literals to create immutable widgets
    sized_box_for_whitespace: true  # Use SizedBox for whitespace in the widget tree
    avoid_returning_null_for_void: true  # Avoid returning null for void functions



    # Lint rules for performance
    avoid_function_literals_in_foreach_calls: true  # Avoid using function literals in forEach calls
    avoid_bool_literals_in_conditional_expressions: true  # Avoid using boolean literals in conditional expressions
    use_colored_box: true  # Use ColoredBox instead of Container with color
