// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMv5mrDVERU249HAzsZems-rJn7JwZEG8',
    appId: '1:468537239102:web:a3789e18ca6bd5ab80136f',
    messagingSenderId: '468537239102',
    projectId: 'slyth-87a2b',
    authDomain: 'slyth-87a2b.firebaseapp.com',
    storageBucket: 'slyth-87a2b.firebasestorage.app',
    measurementId: 'G-76189HSMDN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoP6KLuzt1sJnuiFRyaYkGiTW19pj6fY',
    appId: '1:468537239102:ios:1862b1bb5d2203d180136f',
    messagingSenderId: '468537239102',
    projectId: 'slyth-87a2b',
    storageBucket: 'slyth-87a2b.firebasestorage.app',
    iosBundleId: 'com.example.videoDesktopSaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMv5mrDVERU249HAzsZems-rJn7JwZEG8',
    appId: '1:468537239102:web:bc9ce074b1bec75b80136f',
    messagingSenderId: '468537239102',
    projectId: 'slyth-87a2b',
    authDomain: 'slyth-87a2b.firebaseapp.com',
    storageBucket: 'slyth-87a2b.firebasestorage.app',
    measurementId: 'G-1RNPKPBG6C',
  );
}
